use anyhow::{Context, Result, bail};
use std::path::{Path, PathBuf};
use std::process::Command;

/// Build a Python script into a Wasm component using `componentize-py`.
///
/// Requires `componentize-py` to be installed (`pip install componentize-py`).
pub fn build_python(script: &Path, output: &Path, wit_path: &Path, world: &str) -> Result<()> {
    // Verify componentize-py is available.
    let version_check = Command::new("componentize-py").arg("--version").output();

    match version_check {
        Err(_) => {
            bail!("`componentize-py` not found. Install it with: pip install componentize-py")
        }
        Ok(out) if !out.status.success() => bail!(
            "`componentize-py --version` failed: {}",
            String::from_utf8_lossy(&out.stderr)
        ),
        _ => {}
    }

    let script = script
        .canonicalize()
        .with_context(|| format!("script not found: {}", script.display()))?;

    let wit_path = wit_path
        .canonicalize()
        .with_context(|| format!("wit path not found: {}", wit_path.display()))?;

    // Ensure parent directory of output exists.
    if let Some(parent) = output.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("cannot create output directory: {}", parent.display()))?;
        }
    }

    println!(
        "Building {} → {} (world: {})",
        script.display(),
        output.display(),
        world
    );

    let status = Command::new("componentize-py")
        .args([
            "componentize",
            "--wit-path",
            wit_path.to_str().context("non-UTF-8 wit path")?,
            "--world",
            world,
            script.to_str().context("non-UTF-8 script path")?,
            "-o",
            output.to_str().context("non-UTF-8 output path")?,
        ])
        .status()
        .context("failed to spawn componentize-py")?;

    if !status.success() {
        bail!("componentize-py exited with status {}", status);
    }

    let size = std::fs::metadata(output).map(|m| m.len()).unwrap_or(0);
    println!(
        "✓ Built: {}  ({:.1} KB)",
        output.display(),
        size as f64 / 1024.0
    );

    Ok(())
}

/// Generate a Python stub file that satisfies the `fluxion:task` WIT interface.
///
/// The stub imports the generated bindings and provides a skeleton `process`
/// function that the user fills in.
pub fn generate_python_stub(output_path: &Path) -> Result<()> {
    const STUB: &str = r#"# Auto-generated by `fluxion build python --init`
# Implements the fluxion:task/processor interface.
#
# The `process` function receives:
#   input.content   — bytes payload from the previous job or workflow input
#   input.metadata  — list of (key, value) string pairs
#
# Return a TaskOutput with your result bytes and optional metadata.

from task_component.imports import TaskInput, TaskOutput


def process(input: TaskInput) -> TaskOutput:
    # Decode input, do work, return output.
    data = bytes(input.content).decode("utf-8", errors="replace")
    result = data  # TODO: replace with real logic
    return TaskOutput(
        content=list(result.encode("utf-8")),
        metadata=[("source", "python-component")],
    )
"#;

    std::fs::write(output_path, STUB)
        .with_context(|| format!("cannot write stub to {}", output_path.display()))?;
    println!("✓ Generated stub: {}", output_path.display());
    Ok(())
}

/// Infer the output path from the script path: `hello.py` → `hello.wasm`.
pub fn default_output(script: &Path) -> PathBuf {
    script.with_extension("wasm")
}
